### ISSUE TITLE
Y24-121 - As a developer (Ben) I would like there to be fine-grained batch creation validation for sequencing pipelines

### ISSUE THREAD

**Issue by BenTopping** [sanger/sequencescape#4135]
**User story**
As a developer (Ben) I would like there to be fine-grained batch creation validation for sequencing pipelines.

Currently batch validation for sequencing pipelines lives in a few places, [default records](https://github.com/sanger/sequencescape/blob/develop/config/default_records/pipelines/default_records.yml), [sequencing pipeline model](https://github.com/sanger/sequencescape/blob/develop/app/models/sequencing_pipeline.rb), [batch model](https://github.com/sanger/sequencescape/blob/develop/app/models/batch.rb). This implementation limits any new validation to be added as global validation to every batch (validation in batch.rb). However with some pipelines we want fine grained batch creation behaviour like [NovaSeqX](https://github.com/sanger/sequencescape/issues/4068)

The aim of this story is to enable custom/individual batch validation for each pipeline. There may be a few ways to do this and it may require some investigation prior to implementation. My suggested implementation:

1. Adding a custom validator class for each  required pipeline. This validator would be referenced in the pipeline config or similar. All existing pipelines could fall back on a 'standard' validator class which contains the existing validation. Then we add a validator class for each pipeline that requires custom validation.
2. We would move the current pipeline/batch.rb validation to the 'standard' validator class.
3. Ensure the batch creation javascript works with the updated methods. https://github.com/sanger/sequencescape/blob/develop/app/views/pipelines/show.html.erb contains some logic to fade out unusable requests when creating a batch and this should still work. Also consider whether this can refactored and allow us to use other logic ontop of batch size.

**Who are the primary contacts for this story**
Ben T, Tris B

**Who is the nominated tester for UAT**
Tris B

(May not need UAT as there should be noticeable difference)

**Comment by dasunpubudumal** [comment]
> Adding a custom validator class for each required pipeline. **This validator would be referenced in the pipeline config or similar.** All existing pipelines could fall back on a 'standard' validator class which contains the existing validation. Then we add a validator class for each pipeline that requires custom validation.

Hi @BenTopping, I assume you're suggesting adding a fine-grained validator for each pipeline in [`config/default_records/pipelines/default_records.yml`](https://github.com/sanger/sequencescape/blob/1ce9c00311078c2edd20be75d5ee0ee0da241245/config/default_records/pipelines/default_records.yml)? For example:

```yml
NovaSeqX PE:
  name: NovaSeqX PE
  active: 1
  sti_type: SequencingPipeline
  sorter: 10
  max_size: 8
  summary: 1
  externally_managed: 0
  group_name: Sequencing
  control_request_type_id: 0
  min_size: 8
  request_type_keys:
    - illumina_htp_novaseqx_paired_end_sequencing
  workflow:
    name: NovaSeqX PE
    item_limit: 8
 validator: NovaSeqXPEValidator
```
